version: 2
jobs:
  docker:
    docker:
    - image: docker
    steps:
    - setup_remote_docker:
        docker_layer_caching: true
    - checkout
    - run:
        name: Docker build and push
        command: |
          docker login -u=${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}
          docker build -t ${DOCKER_USERNAME}/utils-docker:latest .
          docker push ${DOCKER_USERNAME}/utils-docker:latest

workflows:
  version: 2
  build:
    jobs:
    - docker:
        filters:
          branches:
            only: master